from uuid import UUID
from typing import Optional, Dict, Any
from src.domain.entities import Profile
from src.domain.interfaces import ProfileRepository, EventProducer, MediaServiceClient
from src.domain.exceptions import ProfileNotFoundError, InvalidProfileDataError

class ProfileService:
    
    def __init__(
        self,
        repository: ProfileRepository,
        event_producer: EventProducer,
        media_client: MediaServiceClient
    ):
        self.repository = repository
        self.event_producer = event_producer
        self.media_client = media_client
    
    async def get_profile(self, user_id: UUID) -> Optional[Profile]:
        """Use case: Get profile by user ID"""
        return await self.repository.get_by_user_id(user_id)
    
    async def create_profile(self, user_id: UUID, username: str, email: str) -> Profile:
        """Use case: Create new profile"""
        # Check if profile already exists
        existing = await self.repository.get_by_user_id(user_id)
        if existing:
            raise InvalidProfileDataError(f"Profile already exists for user: {user_id}")
        
        profile = Profile(
            id=UUID(int=0),  # Will be generated by DB
            user_id=user_id,
            username=username,
            email=email
        )
        return await self.repository.create(profile)
    
    async def update_profile(self, user_id: UUID, updates: Dict[str, Any]) -> Profile:
        """Use case: Update existing profile"""
        profile = await self.repository.get_by_user_id(user_id)
        if not profile:
            raise ProfileNotFoundError(str(user_id))
        
        # Validate updates
        allowed_fields = {'first_name', 'last_name', 'bio', 'avatar_url', 'username', 'email'}
        invalid_fields = set(updates.keys()) - allowed_fields
        if invalid_fields:
            raise InvalidProfileDataError(f"Invalid fields: {invalid_fields}")
        
        # Track changes for event
        old_values = {
            k: getattr(profile, k) 
            for k in updates.keys() 
            if hasattr(profile, k) and getattr(profile, k) != updates[k]
        }
        
        # Apply updates
        profile.update(**updates)
        updated_profile = await self.repository.update(profile)
        
        # Send event about changes (only if there were actual changes)
        if old_values:
            await self.event_producer.send_event(
                "profile_service.profile.changed",
                {
                    "profile_id": str(updated_profile.id),
                    "user_id": str(updated_profile.user_id),
                    "changes": updates,
                    "old_values": old_values
                }
            )
        
        return updated_profile
    
    async def delete_profile(self, user_id: UUID) -> bool:
        """Use case: Delete profile"""
        profile = await self.repository.get_by_user_id(user_id)
        
        # Delete avatar from media service if exists
        if profile and profile.avatar_url:
            await self.media_client.delete_avatar(profile.avatar_url)
        
        return await self.repository.delete(user_id)